FROM debian:bookworm

# APT install
RUN apt-get update && apt-get install -y --no-install-recommends \
        wget \
        libgl1 \
        &&\
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/*

RUN cd / &&\
    wget -nc --no-check-certificate -O /tmp/FreeCAD https://github.com/realthunder/FreeCAD/releases/download/20240123stable/FreeCAD-Link-Stable-Linux-x86_64-py3.11-20240123.AppImage &&\
    chmod a+x /tmp/FreeCAD &&\
    /tmp/FreeCAD --appimage-extract &&\
    rm /tmp/FreeCAD &&\
    mv squashfs-root FreeCAD

RUN sed -i 's|cd $PREFIX/bin||g' /FreeCAD/AppRun &&\
    sed -i 's|"./$name" "$@"|"$PREFIX/bin/$name" "$@"|g' /FreeCAD/AppRun

ENTRYPOINT [ "/FreeCAD/AppRun" ]

CMD [ "FreeCADCmd" ]
